Update add-issue script options

diff --git a/bin/add-issue b/bin/add-issue
--- a/bin/add-issue
+++ b/bin/add-issue
@@ -25,7 +25,8 @@ If change is not found, no action is taken.
     --assignee USER         Github user issue will be assigned to (default @me).
     --issue-id ISSUE        Use issue ISSUE instead of creating a new one.
     --no-update-plan        Do not add URL link to ISSUE in Sqitch project plan.
-    --use-plan-co           Add CR's comment in Sqitch plan to issue body.
+    --use-plan-issue        Use issue in plan instead of creating a new one.
+    --use-plan-comment      Add CR's comment in Sqitch plan to issue body.
     --close-issue           Close issue when done.
 
 Example:
@@ -36,7 +37,12 @@ EOF
 )
 
 function usage() {
+    error_message="$1"
+    if [ ! -z "$error_message" ]; then
+        echo "error: $error_message"
+    fi
     echo "$usage_message"
+    exit 64
 }
 
 g_change=
@@ -49,6 +55,7 @@ g_body="To be documented. Placeholder issue for change request."
 g_close=NO
 g_update_plan=YES
 g_use_plan_comment=NO
+g_use_plan_issue=NO
 g_comment=
 g_issue_id=
 
@@ -94,14 +101,15 @@ do
             g_use_plan_comment="YES";
             shift;
         ;;
+        --use-plan-issue)
+            g_use_plan_issue="YES";
+            shift;
+        ;;
         --help|-h)
             usage
-            exit 0
         ;;
         --*)
-            echo "error: invalid option $1"
-            usage
-            exit 64
+            usage "error: invalid option $1"
         ;;
         *)
             POSITIONAL+=("$1")
@@ -114,27 +122,26 @@ set -- "${POSITIONAL[@]}" # restore positional parameters
 
 
 if [ -z "$g_change" ] || [ -z "$g_body" ]; then
-    echo "error: missing required option --change or --body"
-    exit 64
+    usage "error: missing required option --change or --body"
 fi
 
+if [ ! -z "$g_issue_id" ] || [ "$g_use_plan_issue" == "YES" ]; then
+    usage "error: --issue-id and -use-plan-issue are not mutual exclusive"
+fi
 
 if [ -z "$g_project" ]; then
     g_project=$(find_project "$g_change")
     if [ -z "$g_project" ]; then
-        echo "error: $g_change not found in any project"
-        exit 64
+        usage "error: $g_change not found in any project"
     fi
 fi
 
 if [ ! -f "$g_project/sqitch.plan" ]; then
-    echo "Project $g_project does not exist"
-    exit 64
+    usage "Project $g_project does not exist"
 fi
 
 if [ ! -f "$g_project/deploy/${g_change}.sql" ]; then
-    echo "Change $g_project/deploy/${g_change}.sql does not exist"
-    exit 64
+    usage "Change $g_project/deploy/${g_change}.sql does not exist"
 fi
 
 if [ "$g_use_plan_comment" == "YES" ]; then
@@ -155,6 +162,10 @@ EOF
 # echo $issue_body
 
 g_issue_url=
+
+if [ "$use_plan_issue" == "YES" ]; then
+    g_issue_id=$(get_cr_issue_id "$g_project" "$g_change")
+fi
 
 if [ "$g_issue_id" == "" ]; then
 
