feat: implement schema dump script with PostgreSQL DDL generation

diff --git a/bin/dump-tables-ddl b/bin/dump-tables-ddl
--- a/bin/dump-tables-ddl
+++ b/bin/dump-tables-ddl
@@ -5,25 +5,26 @@ export PGCLIENTENCODING=UTF8
 dothostfile=~/vault/.default.sead.server
 dotuserfile=~/vault/.default.sead.username
 
-target_db_name=
+g_database=sead_staging
+g_schema=public
+g_host=$(dnsdomainname -A)
+g_port=5433
+g_username=
 
-log_file=`date "+%Y%m%d%H%M%S"`_"deploy_${target_db_name}_${source_type}.log"
-
-dbname=sead_staging
-
-if [[ -f "$dothostfile" ]]; then
-    dbhost=`cat $dothostfile`
-fi
+# if [[ -f "$dothostfile" ]]; then
+#     g_host=`cat $dothostfile`
+# fi
 if [[ -f "$dotuserfile" ]]; then
-    dbuser=`cat $dotuserfile`
+    g_username=`cat $dotuserfile`
 fi
 
 usage_message=$(cat <<EOF
-usage: xyz OPTIONS...
+usage: xyz OPTIONS... DATABASE
 
-    --host SERVERNAME               Target server (${dbhost})
-    --user USERNAME                 User on target server (${dbuser})
-    --dbname DBNAME                 Target database name. Mandatory.
+    --host SERVERNAME               Target server (${g_host})
+    --user USERNAME                 User on target server (${g_username})
+    --port PORT                     Port on target server (${g_port})
+    --schema SCHEMANAME             Schema name (${g_schema})
 
 EOF
 )
@@ -35,13 +36,16 @@ do
 
     case $key in
         --host)
-            dbhost="$2"; shift; shift
+            g_host="$2"; shift; shift
         ;;
-        --user)
-            dbuser="$2"; shift; shift
+        --user|-U)
+            g_username="$2"; shift; shift
         ;;
-        --dbname)
-            dbname="$2"; shift; shift
+        --schema|-s)
+            g_schema="$2"; shift; shift
+        ;;
+        --port|-p)
+            g_port="$2"; shift; shift
         ;;
         *)
             POSITIONAL+=("$1") # save it in an array for later
@@ -50,25 +54,33 @@ do
     esac
 done
 
-tables_sql="select string_agg(tablename, ' ') from pg_tables where schemaname = 'public'"
+g_database="${POSITIONAL[0]}"
 
-public_tables=`psql --host=$dbhost --username=$dbuser --no-password --dbname=$dbname -tAc "$tables_sql"`
+if [ "$g_database" == "" ]; then
+    echo "Database name is required." >&2
+    usage
+fi
 
-for dbtable in $public_tables
-do
+# tables_sql="select string_agg(tablename, ' ') from pg_tables where schemaname = 'public'"
+
+# public_tables=`psql --host=$g_host --username=$g_username --no-password --dbname=$g_database -tAc "$tables_sql"`
+
+# for table in $public_tables
+# do
     pg_dump --schema-only \
         --no-owner \
-        --schema-only \
         --no-privileges \
         --format=p \
-        --table=$dbtable \
-        --username=$dbuser \
-        --dbname=$dbname \
-        --schema=public \
-        --host=$dbhost \
-        --no-comments \
+        --username=$g_username \
+        --dbname=$g_database \
+        --schema=$g_schema \
+        --host=$g_host \
+        --port=$g_port \
         --no-security-labels \
-        --no-tablespaces \
-        --file=a.sql
-done
+        --no-tablespaces
+        
+        #  \ --file=a.sql
+
+        # --table=$table \
+# done
 
