Fixed bugs, improved script.

diff --git a/bin/rm-cr b/bin/rm-cr
--- a/bin/rm-cr
+++ b/bin/rm-cr
@@ -4,6 +4,8 @@ SHELL=/bin/bash
 
 set -e
 
+. $(dirname "$0")/utility.sh
+
 usage_message=$(cat <<EOF
 usage: rm-cr OPTIONS...
 
@@ -66,7 +68,7 @@ do
     esac
 done
 
-set -- "${POSITIONAL[@]}" # restore positional parameters
+set -- "${POSITIONAL[@]}"
 
 if [ -z "$g_change" ]; then
     g_change="${POSITIONAL[@]}"
@@ -85,14 +87,23 @@ fi
 for project in $g_projects; do
     if [ -f "$project/deploy/${g_change}.sql" ]; then
         mkdir -p $project/archive/deploy $project/archive/revert $project/archive/verify
-        for type in deploy revert verify ; do
+        for type in deploy revert verify; do
+            if [ ! -f "$project/$type/${g_change}.sql" ]; then
+                echo "Change $project/$type/${g_change}.sql does not exist"
+                exit 64
+            fi
             mv "$project/$type/${g_change}.sql" "$project/archive/$type/${g_change}.sql"
-            grep -e "$g_change" "$project/sqitch.plan" >> "$project/archive/sqitch.history"
-            grep -v -e "$g_change" "$project/sqitch.plan" > "$project/$project/sqitch.plan.tmp"
-            mv -f "$project/sqitch.plan.tmp" "$project/sqitch.plan"
-            echo "Change $project/$g_change moved to ./$project/archive"
-            exit 0
         done
+
+        tag=$(get_change_tag "$project" "$g_change")
+
+        echo "$tag" >> "$project/archive/sqitch.history"
+        grep -e "$g_change" "$project/sqitch.plan" >> "$project/archive/sqitch.history"
+        grep -v -e "$g_change" "$project/sqitch.plan" > "$project/sqitch.plan.tmp"
+        mv -f "$project/sqitch.plan.tmp" "$project/sqitch.plan"
+        echo "Change $project/$g_change moved to ./$project/archive"
+        exit 0
     fi
 done
-
+echo "Change $g_change not found!"
+exit 64
